apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-vulnerabilityreport
spec:
  name: vulnerabilityreport
  artifactTypes: application/sarif+json
  parameters: 
    nestedReferences: application/vnd.cncf.notary.signature
    maximumAge: 24h
    disallowedSeverity:
      - high
      - critical
    denylistCVEs:
      - CVE-2021-44228 # Log4Shell
