apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-vulnerabilityreport
spec:
  name: vulnerabilityreport
  artifactTypes: application/sarif+json
  parameters: 
    schemas:
      application/sarif+json: https://json.schemastore.org/sarif-2.1.0-rtm.5.json
    maximumAge: 24h
    disallowedSeverity:
      - medium
      - high
      - critical
