apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementSystem
metadata:
  name: keymanagementsystem-inline
spec:
  type: azurekeyvault
  parameters:
    vaultURI: https://yourkeyvault.vault.azure.net/
    certificates:
      - name: yourCertName
        version: yourCertVersion # Optional, fetch latest version if empty 
    tenantID:
    clientID: 
